version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=wisdomology
      - POSTGRES_PASSWORD=wisdomology
    ports:
      - "5432:5432"
    volumes:
      - postgresdb:/data/postgresdb

  mongodb:
    image: mongo:6.0.5
    environment:
      - MONGO_INITDB_DATABASE=wisdomology
      - MONGODB_INITDB_ROOT_USERNAME=wisdomology
      - MONGODB_INITDB_ROOT_PASSWORD=wisdomology
    ports:
      - "27017:27017"
#    restart: always # causes issues?
    volumes:
      - ./app-database/data/db:/data/db
      - ./app-database/data/log:/var/log/mongodb
      - ./app-database/init.d:/docker-entrypoint-initdb.d

volumes:
  postgresdb:
